### ISSUE TITLE
Failed Reference when Pushing New Branch

### ISSUE THREAD

**Issue by ALEEF02** [rlespinasse/drawio-export-action#31]
**Describe the bug**
When the action is run on a new branch push, the run fails. This is because the script cannot find the previous reference and uses 0s.

**To Reproduce**
Create a new branch and push a DrawIO file on that branch.

**Expected behavior**
Should reference the last commit from the previous branch

**Screenshots**
![image](https://github.com/rlespinasse/drawio-export-action/assets/12904259/dc6a8187-2aa9-4177-b02e-5c846ba4cdc1)
![image](https://github.com/rlespinasse/drawio-export-action/assets/12904259/9bb8879b-5c65-45b2-9021-20df84867b9e)

**Comment by rlespinasse** [comment]
Currently, the search for the previous reference is not possible based on the branches.

I have opened #37 to try to improve this behavior in the future.
