### ISSUE TITLE
Watch Drawio-export release and propose a PR with the updated version

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/drawio-export-action#4]
Instead of doing this manually, we can use a GitHub Action workflow to periodically watch for newly released versions.

**Comment by supcik** [comment]
I like this idea. I guess that one option could be to use [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) to watch the Docker image version. I could work on this enhancement in that way if you want.
